apiVersion: v1
kind: Service
metadata:
  name: zookeeper-loadbalancer-0
spec:
  #type: LoadBalancer
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: clientPort
      protocol: TCP
      port: 2181
      targetPort: 2181
      NodePort: 32181
    - name: serverPort
      protocol: TCP
      port: 2888
      targetPort: 2888
      NodePort: 32888
    - name: leaderElectionPort
      protocol: TCP
      port: 3888
      targetPort: 3888
      NodePort: 33888
  selector:
    #app: cp-zookeeper
    release: my-confluent-oss
    statefulset.kubernetes.io/pod-name: my-confluent-oss-cp-zookeeper-0
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-loadbalancer-1
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      NodePort: 32182
    - name: serverPort
      protocol: TCP
      port: 2888
      targetPort: 2888
      NodePort: 32889
    - name: leaderElectionPort
      protocol: TCP
      port: 3888
      targetPort: 3888
      NodePort: 33889
  selector:
    #app: cp-zookeeper
    release: my-confluent-oss
    statefulset.kubernetes.io/pod-name: my-confluent-oss-cp-zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-loadbalancer-2
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      NodePort: 32183
    - name: serverPort
      protocol: TCP
      port: 2888
      targetPort: 2888
      NodePort: 32890
    - name: leaderElectionPort
      protocol: TCP
      port: 3888
      targetPort: 3888
      NodePort: 33890
  selector:
    #app: cp-zookeeper
    release: my-confluent-oss
    statefulset.kubernetes.io/pod-name: my-confluent-oss-cp-zookeeper-2
