global:
  # How frequently to scrape targets by default.
  # Default 15s
  scrape_interval: 60s
  # How frequently to evaluate rules.
  # Default 15s
  evaluation_interval: 15s
  # How long until a scrape request times out.
  # Default to 10s.
  # Required because cp-demo is using cpu throttling, so let's leave enough time to fetch the metrics in particular for the first time as it needs to compile all rexps
  scrape_timeout: 30s

rule_files:
  - "alert.rules"

# alerting:
#   alertmanagers:
#     - scheme: http
#       static_configs:
#         - targets:
#             - "alertmanager:9093"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "kafka"
    static_configs:
      - targets:
          - "kafka_1:1234"
          - "kafka_2:1234"
          - "kafka_3:1234"
          - "kafka_4:1234"
        labels:
          env: "dev"

  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zookeeper_1:1234"
          - "zookeeper_2:1234"
          - "zookeeper_3:1234"
          - "zookeeper_4:1234"
          - "zookeeper_5:1234"
          - "zookeeper_6:1234"
          - "zookeeper_7:1234"
          - "zookeeper_8:1234"
        labels:
          env: "dev"

  # - job_name: "connect"
  #   static_configs:
  #     - targets:
  #         - "connect:1234"
  #       labels:
  #         env: "dev"
  #         cluster: "cluster1"

  # - job_name: "streams-demo"
  #   static_configs:
  #     - targets:
  #         - "streams-demo:1234"
  #       labels:
  #         env: "dev"
  #
  # - job_name: "schemaregistry"
  #   static_configs:
  #     - targets:
  #         - "schemaregistry:1234"
  #       labels:
  #         env: "dev"
  #
  # - job_name: "ksql"
  #   static_configs:
  #     - targets:
  #         - "ksqldb-server:1234"
  #       labels:
  #         env: "dev"
  #
  # - job_name: "restproxy"
  #   static_configs:
  #     - targets:
  #         - "restproxy:1234"
  #       labels:
  #         env: "dev"

  # No producer for the moment in cp-demo
  #  - job_name: 'producer'
  #    static_configs:
  #      - targets:
  #          - 'producer:1234'
  #        labels:
  #          env: 'dev'

  # No consumer for the moment in cp-demo
  #  - job_name: 'consumer'
  #    static_configs:
  #      - targets:
  #          - "consumer:1234"
  #        labels:
  #          env: 'dev'

  # - job_name: "kafka-lag-exporter"
  #   static_configs:
  #     - targets:
  #         - "kafka-lag-exporter:9999"
  #       labels:
  #         env: "dev"
