
apiVersion: v1
kind: Service
metadata:
  name: confluent-cp-control-lb
  namespace: confluent
  labels:
    app: cp-control-center
spec:
  #type: LoadBalancer
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 9021
      targetPort: 9021
  selector:
    app: cp-control-center
    release: confluent
