apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: confluent
spec:
  type: ExternalName
  externalName: a10d1bec289954ca69f42bfc8a5d7709-1005039869.ap-southeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-4
  namespace: confluent
spec:
  type: ExternalName
  externalName: af8f4be5bae9f41e4b0fb8c329a68a11-1765115105.ap-southeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-5
  namespace: confluent
spec:
  type: ExternalName
  externalName: aff6e1ba2d8a04846ba6b369309cd225-1729163824.ap-southeast-2.elb.amazonaws.com
