
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-0
  namespace: confluent
spec:
  #type: LoadBalancer
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32181
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32888
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 3888
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-0
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: confluent
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32182
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32889
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 33889
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  namespace: confluent
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32183
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32890
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 33890
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-2
    
