apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: confluent
spec:
  type: ExternalName
  externalName: a286e214220874742bd52914a956c93e-1486539011.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-4
  namespace: confluent
spec:
  type: ExternalName
  externalName: a6a41845f998a4cbc9a8e7e349f427aa-1927252033.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-5
  namespace: confluent
spec:
  type: ExternalName
  externalName: aeea51b96d07548eda29af126f558c3f-1967556870.ap-northeast-2.elb.amazonaws.com
