apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: confluent
spec:
  type: ExternalName
  externalName: aaf56985a0f084f4893def91d0fcd2d8-1545462266.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-4
  namespace: confluent
spec:
  type: ExternalName
  externalName: a3206654513f849ab83f2cd9e9e83640-1344639289.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-5
  namespace: confluent
spec:
  type: ExternalName
  externalName: afcf28b3f00d74443a13d0077fe3c094-628156109.ap-northeast-2.elb.amazonaws.com
