apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: confluent
spec:
  type: ExternalName
  externalName: a9a2013e9c8054763a09dc5a301c624f-50538533.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-4
  namespace: confluent
spec:
  type: ExternalName
  externalName: a878f1cd547234ee3837ea1f13f3b763-1221536849.ap-northeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-5
  namespace: confluent
spec:
  type: ExternalName
  externalName: a9ddaace35eff41ffac9406f40783c45-1100808932.ap-northeast-2.elb.amazonaws.com
