# Source: cp-helm-charts/charts/cp-zookeeper/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: confluent-cp-zookeeper
  namespace: confluent
  labels:
    app: cp-zookeeper
    chart: cp-zookeeper-0.1.0
    release: confluent
    heritage: Helm
spec:
  selector:
    matchLabels:
      app: cp-zookeeper
      release: confluent
  serviceName: confluent-cp-zookeeper-headless
  podManagementPolicy: OrderedReady
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cp-zookeeper
        release: confluent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5556"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - cp-zookeeper
                  - key: "release"
                    operator: In
                    values:
                    - confluent
              topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: pem-to-keystore
        image: "confluentinc/cp-zookeeper:6.1.0"
        env:
        - name: rootca
          value: /etc/ssl/certs/confluent/cp-RootCA.pem
        - name: truststore_jks
          value: /var/run/secrets/confluent.io/keystores/truststore.jks
        - name: keystore_jks
          value: /var/run/secrets/confluent.io/keystores/keystore.jks
        - name: quorum_keystore_jks
          value: /var/run/secrets/confluent.io/keystores/keystore.quorum.jks
        - name: quorum_truststore_jks
          value: /var/run/secrets/confluent.io/keystores/truststore.quorum.jks
        - name: keystorepass
          value: keystorepass
        - name: truststorepass
          value: truststorepass
        command:
        - "bash"
        - "-c"
        - |
          export SERVER_CERT=/etc/ssl/certs/confluent/zookeeper-${HOSTNAME##*-}.crt.pem ;
          export SERVER_KEY=/etc/ssl/certs/confluent/zookeeper-${HOSTNAME##*-}.key.pem ;
          openssl pkcs12 -export -in $SERVER_CERT -CAfile $rootca -inkey $SERVER_KEY -name ${HOSTNAME} -chain -out /tmp/server.p12 -password pass:$keystorepass ;
          keytool -importkeystore -srckeystore /tmp/server.p12 -destkeystore $keystore_jks -srcstoretype pkcs12 -alias ${HOSTNAME} -storepass $keystorepass -keypass $keystorepass -srcstorepass $keystorepass ;
          keytool -noprompt -keystore $truststore_jks -alias CARoot -importcert -file $rootca -storepass $truststorepass -keypass $truststorepass ;
          for i in $(ls /etc/ssl/certs/confluent/*.crt.pem); do keytool -noprompt -importcert -alias $i -file $i -keystore $truststore_jks -trustcacerts -storepass $truststorepass; done
          export SERVER_QUORUM_CERT=/etc/ssl/certs/zookeeper.quorum/zookeeper-${HOSTNAME##*-}.quorum.crt.pem ;
          export SERVER_QUORUM_KEY=/etc/ssl/certs/zookeeper.quorum/zookeeper-${HOSTNAME##*-}.quorum.key.pem ;
          openssl pkcs12 -export -in $SERVER_QUORUM_CERT -CAfile $rootca -inkey $SERVER_QUORUM_KEY -name ${HOSTNAME} -chain -out /tmp/server.quorum.p12 -password pass:$keystorepass ;
          keytool -importkeystore -srckeystore /tmp/server.quorum.p12 -destkeystore $quorum_keystore_jks -srcstoretype pkcs12 -alias ${HOSTNAME} -storepass $keystorepass -keypass $keystorepass -srcstorepass $keystorepass ;
          keytool -noprompt -keystore $quorum_truststore_jks -alias CARoot -importcert -file $rootca -storepass $truststorepass -keypass $truststorepass ;
          for i in $(ls /etc/ssl/certs/zookeeper.quorum/*.crt.pem); do keytool -noprompt -importcert -alias $i -file $i -keystore $quorum_truststore_jks -trustcacerts -storepass $truststorepass; done

        volumeMounts:
        - name: confluent-platform-certificates
          mountPath: /etc/ssl/certs/confluent
        - name: confluent-zk-quorum-certificates
          mountPath: /etc/ssl/certs/zookeeper.quorum
        - name: keystore-volume
          mountPath: /var/run/secrets/confluent.io/keystores
      containers:
      - name: prometheus-jmx-exporter
        image: "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143"
        imagePullPolicy: "IfNotPresent"
        command:
        - java
        - -XX:+UnlockExperimentalVMOptions
        - -XX:+UseCGroupMemoryLimitForHeap
        - -XX:MaxRAMFraction=1
        - -XshowSettings:vm
        - -jar
        - jmx_prometheus_httpserver.jar
        - "5556"
        - /etc/jmx-zookeeper/jmx-zookeeper-prometheus.yml
        ports:
        - containerPort: 5556
        resources:
          {}
        volumeMounts:
        - name: jmx-config
          mountPath: /etc/jmx-zookeeper
      - name: cp-zookeeper-server
        image: "confluentinc/cp-zookeeper:6.1.0"
        imagePullPolicy: "IfNotPresent"
        securityContext:
          runAsUser: 0
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        - containerPort: 5555
          name: jmx
        resources:
          {}
        env:
        - name : KAFKA_HEAP_OPTS
          value: "-Xms512M -Xmx512M"
        - name : KAFKA_JMX_PORT
          value: "5555"
        - name : ZOOKEEPER_TICK_TIME
          value: "4000"
        - name : ZOOKEEPER_SYNC_LIMIT
          value: "5"
        - name : ZOOKEEPER_INIT_LIMIT
          value: "10"
        - name : ZOOKEEPER_MAX_CLIENT_CNXNS
          value: "60"
        - name : ZOOKEEPER_AUTOPURGE_SNAP_RETAIN_COUNT
          value: "3"
        - name : ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
          value: "24"
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name : ZOOKEEPER_SERVERS
          value: "zookeeper-0.confluent:2888:3888;zookeeper-1.confluent:2888:3888;zookeeper-2.confluent:2888:3888;zookeeper-3.confluent:2888:3888;zookeeper-4.confluent:2888:3888;zookeeper-5.confluent:2888:3888"
#          value: "confluent-cp-zookeeper-0.confluent-cp-zookeeper-headless.confluent:2888:3888;confluent-cp-zookeeper-1.confluent-cp-zookeeper-headless.confluent:2888:3888;confluent-cp-zookeeper-2.confluent-cp-zookeeper-headless.confluent:2888:3888"
        #Zookeeper Hierarhical Quorums
        - name: ZOOKEEPER_GROUPS
          value:  "1:2:3;4:5:6"
        - name: ZOOKEEPER_WEIGHTS
          value: "1;1;1;1;1;1"
        # ZOOKEEPER_SERVER_ID is required just to pass cp-zookeeper ensure script for env check,
        # the value(metadata.mame) is not used and will be overwritten in command part
        - name: ZOOKEEPER_SERVER_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ## New settings for ssl
#        - name: truststore_jks
#          value: /var/run/secrets/confluent.io/keystores/truststore.jks
#        - name: keystore_jks
#          value: /var/run/secrets/confluent.io/keystores/keystore.jks
#        - name: keystorepass
#          value: keystorepass
#        - name: truststorepass
#          value: truststorepass
        - name: ZOOKEEPER_SSL_CLIENT_AUTH
          value: "none"
        - name: ZOOKEEPER_SECURE_CLIENT_PORT
          value: "2182"
        - name: ZOOKEEPER_SERVER_CNXN_FACTORY
          value: "org.apache.zookeeper.server.NettyServerCnxnFactory"
        - name: "ZOOKEEPER_AUTH_PROVIDER_X509"
          value: "org.apache.zookeeper.server.auth.X509AuthenticationProvider"
        - name: ZOOKEEPER_SSL_KEYSTORE_LOCATION
          value: /var/run/secrets/confluent.io/keystores/keystore.jks
        - name: ZOOKEEPER_SSL_KEYSTORE_PASSWORD
          value: keystorepass
#        - name: ZOOKEEPER_SSL_KEYSTORE_TYPE
#          value:
        - name: ZOOKEEPER_SSL_TRUSTSTORE_LOCATION
          value: /var/run/secrets/confluent.io/keystores/truststore.jks
        - name: ZOOKEEPER_SSL_TRUSTSTORE_PASSWORD
          value: truststorepass
#        - name: ZOOKEEPER_SSL_KEYSTORE_TYPE
#          value:
        - name: ZOOKEEPER_SSL_QUORUM
          value: "true"
        - name: ZOOKEEPER_SSL_QUORUM_CLIENT_AUTH
          value: "none"
        - name: ZOOKEEPER_SSL_QUORUM_KEYSTORE_LOCATION
          value: /var/run/secrets/confluent.io/keystores/keystore.quorum.jks
        - name: ZOOKEEPER_SSL_QUORUM_KEYSTORE_PASSWORD
          value: keystorepass
#        - name: ZOOKEEPER_SSL_QUORUM_KEYSTORE_TYPE
#          value:
        - name: ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_LOCATION
          value: /var/run/secrets/confluent.io/keystores/truststore.quorum.jks
        - name: ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_PASSWORD
          value: truststorepass
#        - name: ZOOKEEPER_SSL_QUORUM_TRUSTSTORE_TYPE
#          value:
        command:
        - "bash"
        - "-c"
        - |
          ZK_FIX_HOST_REGEX="s/zookeeper-${HOSTNAME##*-}\.[^:]*:/0.0.0.0:/g"
          ZOOKEEPER_SERVER_ID=$((${HOSTNAME##*-}+4)) \
          ZOOKEEPER_SERVERS=`echo $ZOOKEEPER_SERVERS | sed -e "$ZK_FIX_HOST_REGEX"` \
          /etc/confluent/docker/run
        volumeMounts:
        - name: confluent-platform-certificates
          mountPath: /etc/ssl/certs/confluent/
        - name: keystore-volume
          mountPath: /var/run/secrets/confluent.io/keystores
        - name: datadir
          mountPath: /var/lib/zookeeper/data
        - name: datalogdir
          mountPath: /var/lib/zookeeper/log
      volumes:
      - name: jmx-config
        configMap:
          name: confluent-cp-zookeeper-jmx-configmap
      - name: keystore-volume
        emptyDir:
          medium: Memory
      - name: confluent-platform-certificates
        configMap:
          name: confluent-platform-certificates
      - name: confluent-zk-quorum-certificates
        configMap:
            name: confluent-zk-quorum-certificates
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "10Gi"
  - metadata:
      name: datalogdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: "10Gi"
