
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-3
  namespace: confluent
spec:
  #type: LoadBalancer
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32181
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32888
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 3888
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-0
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-4
  namespace: confluent
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32182
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32889
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 33889
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-5
  namespace: confluent
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: client
      protocol: TCP
      port: 2181
      targetPort: 2181
      #NodePort: 32183
    - name: serverport
      protocol: TCP
      port: 2888
      targetPort: 2888
      #NodePort: 32890
    - name: leaderelectionport
      protocol: TCP
      port: 3888
      targetPort: 3888
      #NodePort: 33890
  selector:
    #app: cp-zookeeper
    release: confluent
    statefulset.kubernetes.io/pod-name: confluent-cp-zookeeper-2

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-0
  namespace: confluent
spec:
  type: ExternalName
  externalName: a9dbb8d03ada7416293c90e4337c3eda-992348493.ap-southeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
  namespace: confluent
spec:
  type: ExternalName
  externalName: afa7ff3b33f114b82aa5d6d61def9b84-1094228810.ap-southeast-2.elb.amazonaws.com
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-2
  namespace: confluent
spec:
  type: ExternalName
  externalName: a4a25840bd7b14c329d3d22700756f43-1649301520.ap-southeast-2.elb.amazonaws.com
