apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cstow-dc0
  region: ap-southeast-2

vpc:
  cidr: 10.10.0.0/16
  autoAllocateIPv6: true
  
  clusterEndpoints:
    publicAccess: true
    privateAccess: true


nodeGroups:
  - name: ng-0-1
    instanceType: t3.medium
    desiredCapacity: 3
