apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cstow-dc2
  region: ap-southeast-2

vpc:
  cidr: 10.12.0.0/16
  autoAllocateIPv6: true
  # disable public access to endpoint and only allow private access
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

nodeGroups:
  - name: ng-2-1
    instanceType: t3.medium
    desiredCapacity: 3
